version: '3'
services:
  redis_container:
    image: redis
    restart: unless-stopped
  mongo_container:
    image: mongo:${MONGO_VERSION:-4.4}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
    restart: unless-stopped
    volumes:
      - mongo_data:/data
  app:
    user: node
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis_container
      - mongo_container
    volumes:
      - ..:/home/node/workspace:cached
      - dist:/home/node/workspace/dist:cached
      - vscode-server-extensions:/home/node/.vscode-server/extensions
      - node_modules:/home/node/workspace/node_modules
      - zsh_history:/home/node/zsh_history
    command: /bin/sh -c "while sleep 1000; do :; done"
volumes:
  vscode-server-extensions:
  zsh_history:
  node_modules:
  mongo_data:
  dist:

    # Consider clone in container feature from https://code.visualstudio.com/remote/advancedcontainers/improve-performance